executor: local
use-conda: True
restart-times: 0
cores: 32
resources:
  ena_api_calls_per_second: 50
  sqlite_connections: 1
default-resources:
  mem_mb: 4000
  threads: 1
  runtime: 60
rerun-incomplete: True
consider-ancient:
  split_ena_search_results: table
scheduler: greedy
