from pathlib import Path
import functools
import csv

configfile: "config/config.yaml"


include: "rules/common.smk"


rule all:
    input:
        "output/ena/search.tsv",
        "output/ena/summarize_ena_search/summary.png",
        "output/ena/summarize_ena_search_pangolin/summary.png",
        lambda w: build_pangolin_targets(w, "output/preproc/multiqc/{}", ("study_accession",)),
        lambda w: build_pangolin_targets(w, "output/variants/variant_calling/{}/{}/{}/{}/{}_{}_{}/sample.annotated.vcf"),
        expand("output/variants/snpsift_haplotype_merge/{haplotype}.annotated.filtered.vcf", haplotype=config["HAPLOTYPES"].keys()),
        "output/repdel/report_region/region.png"


include: "rules/fetch.smk"
include: "rules/ena.smk"
include: "rules/preproc.smk"
include: "rules/mapping.smk"
include: "rules/variants.smk"
include: "rules/pangolin.smk"
include: "rules/repdel.smk"
