from pathlib import Path
import functools
import csv

configfile: "config/config.yaml"
include: "rules/common.smk"

OUTPUT = Path(config["OUTPUT"])


rule all:
    input:
        OUTPUT/"ena/search.tsv",
        OUTPUT/"ena/summarize_ena_search/summary.png",
        OUTPUT/"ena/summarize_ena_search_after_processing/summary.png",
        lambda w: build_afterproc_targets(w, OUTPUT/"preproc/multiqc/{}", ("study_accession",)),
        expand(
            OUTPUT/"repdel/filter_haplotype/{haplotype}.inclpct_{inclpct}.exclpct_{exclpct}.csv",
            haplotype=config["HAPLOTYPES"].keys(),
            inclpct=config["MIN_INCLUDE_FREQ"],
            exclpct=config["MAX_EXCLUDE_FREQ"]
        ),
        lambda w: build_afterproc_targets(w, OUTPUT/"repdel/report_region/{}/{}/{}/{}/{}_{}_{}/sample.png")


include: "rules/fetch.smk"
include: "rules/ena.smk"
include: "rules/preproc.smk"
include: "rules/mapping.smk"
include: "rules/variants.smk"
include: "rules/pangolin.smk"
include: "rules/repdel.smk"
