executor: slurm
use-conda: True
jobs: 64
printshellcmds: True
restart-times: 0
default-resources:
  nodes: 1
  ntasks: 1
  mem_mb: 4000
  threads: 2
  slurm_partition: "'global'"
  slurm_extra: "'--qos=short'"
  runtime: 60
resources:
  ebi_api_calls_per_second: 50
set-resources:
  download_ena_one_fastq:
    ebi_api_calls_per_second: 1
  download_ena_two_fastq:
    ebi_api_calls_per_second: 1
