executor: slurm
use-conda: True
jobs: 1000
cores: 200
slurm-requeue: True
printshellcmds: True
restart-times: 1
max-status-checks-per-second: 1
max-jobs-per-timespan: 20/1s
latency-wait: 60
resources:
  ena_api_calls_per_second: 50
  sqlite_connections: 1
default-resources:
  mem_mb: 4000
  slurm_partition: "'global'"
  slurm_extra: "'--qos=short'"
  slurm_account: pgo
  runtime: 30
group-components:
  sample: 8
  download: 5
scheduler: greedy
rerun-incomplete: True
consider-ancient:
  split_ena_search_results: database
