executor: slurm
use-conda: True
jobs: 64
printshellcmds: True
restart-times: 0
default-resources:
  nodes: 1
  ntasks: 1
  mem_mb: 4000
  threads: 2
  slurm_partition: "'global'"
  slurm_extra: "'--qos=short'"
  runtime: 60
set-resources:
  # Set maximum limits for the EBI API (50/s)
  download_ena_one_fastq:
    jobs: 24
  download_ena_two_fastq:
    jobs: 24
