executor: slurm
use-conda: True
jobs: 64
printshellcmds: True
restart-times: 0
default-resources:
  nodes: 1
  ntasks: 1
  mem_mb: 4000
  slurm_partition: "'global'"
  slurm_extra: "'--qos=short'"
  runtime: 30
resources:
  ena_api_calls_per_second: 50
group-components:
   group_{run}: 20
