executor: slurm
use-conda: True
jobs: 64
printshellcmds: True
restart-times: 1
default-resources:
  nodes: 1
  ntasks: 1
  mem_mb: 4000
  slurm_partition: "'global'"
  slurm_extra: "'--qos=short'"
  runtime: 30
resources:
  ena_api_calls_per_second: 50
group-components:
  group_{study}: 20
  group_pangolin: 8
  group_preproc: 32
  group_mapping: 16
  group_variants: 32
set-resources:
  group_{study}:
    threads: 20
    nodes: 1
  group_pangolin:
    threads: 64
    nodes: 1
  group_preproc:
    threads: 32
    nodes: 1
  group_mapping:
    threads: 64
    nodes: 1
  group_variants:
    threads: 32
    nodes: 1
