OUTPUT: output
PY_LOG_FMT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
SEARCH_TABLE: "search.tsv"
REFERENCE: "clinical_BA1"  # OZ070629.1
SNPEFF:
  DATADIR: "data/snpEff/data"
  CONFIG: "data/snpEff/my_snpEff.config"
REPORT:
  START: 21724  # 20 nts before S:p.Val67_Ile68dup (rep S:69/70)
  END:   21980  # 20 nts after S:p.Asp140_His141insValTyrTyr (rep S:143/145)
MIN_INCLUDE_FREQ:
  - 95
  - 70
MAX_EXCLUDE_FREQ:
  - 5
  - 30
HAPLOTYPES:
  # Rep69/70 == S:p.Val67_Ile68dup
  # Rep143/145 == S:p.Asp140_His141insValTyrTyr
  Rep_69_70:
    include_hgvs_p:
      - gene: S
        expression: p.Val67_Ile68dup
    exclude_hgvs_p:
      - gene: S
        expression: p.Asp140_His141insValTyrTyr
  Rep_143_145:
    include_hgvs_p:
      - gene: S
        expression: p.Asp140_His141insValTyrTyr
    exclude_hgvs_p:
      - gene: S
        expression: p.Val67_Ile68dup
  Rep_Both:
    include_hgvs_p:
      - gene: S
        expression: p.Val67_Ile68dup
      - gene: S
        expression: p.Asp140_His141insValTyrTyr
