executor: slurm
use-conda: True
jobs: 1
printshellcmds: True
restart-times: 0
default-resources:
  nodes: 1
  ntasks: 1
  mem_mb: 8000
  threads: 2
  slurm_partition: "'global'"
  slurm_extra: "'--qos=short'"
  runtime: 180  # 3h
keep-incomplete: True
notemp: True
rerun-incomplete: True
resources:
  ebi_api_calls_per_second: 50
set-resources:
  download_ena_one_fastq:
    ebi_api_calls_per_second: 1
  download_ena_two_fastq:
    ebi_api_calls_per_second: 1
